### ISSUE TITLE
Error 1064 SQL syntax

### ISSUE THREAD

**Issue by Untuouchum** [Critical-Start/pastebin_scraper#5] opened 2019-03-22 16:52 UTC
Hi!!
First of all many thanks for the project. I find it very useful.

I've configured a MySQL db and did the steps below, then get this error  :

-----------------------------------------------------------------------------------------------------------------------
2019-03-22 17:44:38,132 [INFO] [*] FOUND DB_DUMP https://scrape.pastebin.com/api_scrape_item.php?i=*****
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/pastebin_scraper/pastebin_scraper/lib/Site.py", line 80, in monitor
    cursor.execute("INSERT INTO pastes (pid, text, emails, hashes, num_emails, num_hashes, type, db_keywords, url, author) VALUES (\""+str(paste.id)+"\",\""+str(paste.text)+"\",\""+str(paste.emails)+"\",\""+str(paste.hashes)+"\",\""+str(paste.num_emails)+"\",\""+str(paste.num_hashes)+"\",\""+str(paste.type)+"\",\""+str(paste.db_keywords)+"\",\""+str(paste.url)+"\",\""+str(paste.author)+"\")")
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'ISO CODES" to add/delete countries\r\nCountryCheck:\r\n  Active: true\r\n  Mode: 1\r\n  \' at line 1')
-----------------------------------------------------------------------------------------------------------------------

I found online errors on reserved words (alter )  but can't make the connection tomy error now. 
How can I have detailed logs or can you tell me what's wrong please ? 

Thanks in advance

**Comment by Untuouchum** [comment] 2019-03-22 16:55
Hi,

In fact I have other errors like this one after launching this in SQL mode :

One other :
sql.err.ProgrammingError: (1064, 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'https://raw.github.com/iChun/Morph/master/src/main/resources/assets/morph/mod/"\r\' at line 1')

**Comment by wedemmoez** [comment] 2019-03-25 17:08
Duplicate of #2 

There is currently an issue with some pastes using double quotes which breaks the SQL syntax. I've pushed a temporary workaround 4 days ago that causes the script to not crash. It will leave a log for a user to manually review that paste.

**Closed by wedemmoez** 2019-03-25 17:08 UTC
