### ISSUE TITLE
JSON object Error

### ISSUE THREAD

**Issue by stuttgartPSE** [Critical-Start/pastebin_scraper#6] opened 2019-03-25 15:02 UTC
It seems that there's an error in your code. I have deployed the original code from your project. But it gives me this error:

> 2019-03-25 15:53:24,840 [INFO] Monitoring...
> 2019-03-25 15:53:24,849 [INFO] Retrieving Pastebin ID's
> Exception in thread Thread-1:
> Traceback (most recent call last):
>   File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.5/threading.py", line 862, in run
>     self._target(*self._args, **self._kwargs)
>   File "/opt/pastebin_scraper/lib/Site.py", line 68, in monitor
>     self.update()
>   File "/opt/pastebin_scraper/lib/Pastebin.py", line 45, in update
>     raw_json = json.load(raw)
>   File "/usr/lib/python3.5/json/__init__.py", line 268, in load
>     parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
>   File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
>     s.__class__.__name__))
> TypeError: the JSON object must be str, not 'bytes'

Maybe I don't have the correct requirements needed??

**Comment by wedemmoez** [comment] 2019-03-25 17:10
Duplicate of #3 

This occurs when you do not have your IP whitelisted in the Pastebin Scraping API. [More info here](https://pastebin.com/doc_scraping_api)

**Closed by wedemmoez** 2019-03-25 17:10 UTC
